<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Métodos y Simulación Estadística" />


<title> Problema No. 1. Normal bivariada</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"> </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Inicio
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Probabilidad
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso101.html">Introducción</a>
    </li>
    <li>
      <a href="recurso102.html">Conceptos básicos</a>
    </li>
    <li>
      <a href="recurso103.html">Enfoques y postulados</a>
    </li>
    <li>
      <a href="recurso104.html">Tipos de probabilidad</a>
    </li>
    <li>
      <a href="recurso104b.html">Independencia</a>
    </li>
    <li>
      <a href="recurso104c.html">Teorema de Bayes</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Variable aleatoria
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso201.html">Variable aleatoria: Univariado</a>
    </li>
    <li>
      <a href="recurso202.html">Valor esperado</a>
    </li>
    <li>
      <a href="recurso203.html">Variables conjuntas</a>
    </li>
    <li>
      <a href="recurso204.html">Modelos discretos: Univariado</a>
    </li>
    <li>
      <a href="recurso205.html">Modelos continuos: Univariado</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Inferencia estadística
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso301.html">Conceptos básicos</a>
    </li>
    <li>
      <a href="recurso302.html">Distribución muestral</a>
    </li>
    <li>
      <a href="recurso305.html">Teorema del límite central</a>
    </li>
    <li>
      <a href="recurso303.html">Propiedades de los estimadores</a>
    </li>
    <li>
      <a href="recurso304.html">Métodos de estimación</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Intervalos de confianza
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso401.html">Paramétrico: Una población</a>
    </li>
    <li>
      <a href="recurso402.html">Paramétrico: Dos poblaciones</a>
    </li>
    <li>
      <a href="recurso403.html">Estimación no paramétrica</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Pruebas de hipótesis
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso501.html">Introducción</a>
    </li>
    <li>
      <a href="recurso502.html">Paramétrico: Una población</a>
    </li>
    <li>
      <a href="recurso503.html">Paramétrico: Dos poblaciones</a>
    </li>
    <li>
      <a href="recurso504.html">Pruebas no paramétricas</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Casos y simulaciones
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso404.html">Casos 1 y 2</a>
    </li>
    <li>
      <a href="recurso406.html">Simulación y problema</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Referencias
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso1000.html">Referencias</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore"><span style="color:#686868">
<strong>Problema No. 1. Normal bivariada</strong></span></h1>
<h4 class="author">Métodos y Simulación Estadística</h4>

</div>


</br></br>
<div class="caja-ejemplo">
<h3>
Problema 1:
</h3>
<p>
<p>Una fábrica de mecanizado de precisión produce ejes metálicos
utilizados en motores eléctricos de maquinaria industrial. Estos
componentes deben cumplir con altos estándares de calidad, ya que
cualquier desviación en sus dimensiones o en la calidad de la superficie
puede afectar el ensamblaje, el rendimiento y la vida útil del
motor.</p>
<p>En este proceso de fabricación, dos variables clave determinan la
calidad del eje:</p>
<ul>
<li><p><strong><span class="math inline">\(X\)</span> : Diámetro del eje
(en milímetros, mm)</strong></p></li>
<li><p><strong><span class="math inline">\(Y\)</span> : Rugosidad
superficial del eje (en micrómetros, <span class="math inline">\(\mu
m\)</span>)</strong></p></li>
</ul>
<p>El <strong>diámetro y la rugosidad</strong>, se pueden modelar
mediante una <strong>distribución normal bivariada</strong>, expresada
como:</p>
<p><span class="math display">\[
(X, Y) \sim N_2 \left(
\boldsymbol{\mu},  
\Sigma
\right)
\]</span></p>
<p>donde:</p>
<ul>
<li><p><span class="math inline">\(\boldsymbol{\mu}\)</span> representa
el <strong>vector de medias</strong> del proceso.</p></li>
<li><p><span class="math inline">\(\Sigma\)</span> es la <strong>matriz
de covarianza</strong>, que describe la dispersión conjunta de ambas
variables.</p></li>
</ul>
<p>El propósito de este análisis es <strong>evaluar la conformidad del
proceso de fabricación</strong>, mediante el cálculo de:</p>
<ul>
<li><p>La probabilidad de que un eje cumpla simultáneamente con las
especificaciones de <strong>diámetro y rugosidad</strong>.</p></li>
<li><p>La probabilidad de que un eje tenga una <strong>rugosidad
aceptable</strong> dado que su <strong>diámetro está dentro del rango
especificado</strong>.</p></li>
<li><p>La <strong>rugosidad esperada</strong> para un diámetro
específico, lo que permitirá prever la calidad superficial de los ejes
en producción.</p></li>
</ul>
<p>Este estudio permitirá <strong>determinar si el control del diámetro
es suficiente para garantizar la calidad de la rugosidad</strong> o si
se requieren <strong>ajustes adicionales en el proceso de
mecanizado</strong>.</p>
<p>Para analizar la conformidad del proceso de fabricación, se presentan
a continuación:</p>
<ul>
<li><p><strong>Parámetros del modelo normal bivariado</strong>: Se
definen las medias, varianzas y covarianza del diámetro del eje y la
rugosidad superficial.</p></li>
<li><p><strong>Función de densidad conjunta</strong>: Se describe
matemáticamente la distribución conjunta de <span
class="math inline">\(X\)</span> y <span
class="math inline">\(Y\)</span>, lo que permite modelar su
comportamiento probabilístico.</p></li>
<li><p><strong>Representación gráfica</strong>: Se visualiza la densidad
conjunta mediante:</p>
<ul>
<li><p>Un <strong>gráfico tridimensional</strong>, que muestra la forma
de la distribución.</p></li>
<li><p>Un <strong>mapa de calor con curvas de nivel</strong>, que
permite identificar las combinaciones más probables de diámetro y
rugosidad.</p></li>
</ul></li>
</ul>
<p>Estos elementos permitirán comprender cómo se distribuyen los valores
del diámetro y la rugosidad en el proceso de fabricación y evaluar la
probabilidad de conformidad con las especificaciones establecidas.</p>
<hr />
<p><strong>Parámetros</strong>:</p>
<p><br/> <strong>Medias</strong></p>
<p><span class="math display">\[
\boldsymbol{\mu}=\begin{bmatrix}
\mu_X \\ \mu_Y
\end{bmatrix} =
\begin{bmatrix}
50.00 \\ 1.0
\end{bmatrix}
\]</span></p>
<ul>
<li><p><strong><span class="math inline">\(\mu_X = 50.00\)</span>
mm</strong> → <strong>Diámetro nominal del eje</strong>.</p></li>
<li><p><strong><span class="math inline">\(\mu_Y = 1.0\)</span> <span
class="math inline">\(\mu m\)</span></strong> → <strong>Rugosidad
superficial promedio</strong>.</p></li>
</ul>
<p><br/> <strong>Matriz de covarianza</strong></p>
<p>En la normal bivariada se cumple que <span
class="math inline">\(\text{Cov}(X, Y) = \rho \sigma_X
\sigma_Y\)</span>, por tanto, la matriz de covarianzas queda como se
muestra a continuación:</p>
<p><span class="math display">\[
\begin{align}
\Sigma &amp;=
\begin{bmatrix}
\text{Cov}(X, X) &amp; \text{Cov}(X, Y) \\
\text{Cov}(X, Y) &amp; \text{Cov}(Y, Y)
\end{bmatrix}  \\
&amp;=
\begin{bmatrix}
\sigma_X^2 &amp; \text{Cov}(X, Y) \\
\text{Cov}(X, Y) &amp; \sigma_Y^2
\end{bmatrix}  \\
&amp;=
\begin{bmatrix}
\sigma_X^2 &amp; \rho \sigma_X \sigma_Y \\
\rho \sigma_X \sigma_Y &amp; \sigma_Y^2
\end{bmatrix}  \\
&amp;=
\begin{bmatrix}
0.015^2 &amp; -0.6 \times (0.015) \times (0.2) \\
-0.6 \times (0.015) \times (0.2) &amp; 0.2^2
\end{bmatrix}  \\
&amp;=
\begin{bmatrix}
0.000225 &amp; -0.0018 \\
-0.0018 &amp; 0.04
\end{bmatrix}  
\end{align}
\]</span></p>
<p>Donde:</p>
<ul>
<li><p><strong><span class="math inline">\(\sigma_X = 0.015\)</span>
mm</strong> → <strong>Desviación estándar del
diámetro</strong>.</p></li>
<li><p><strong><span class="math inline">\(\sigma_Y = 0.2\)</span> <span
class="math inline">\(\mu m\)</span></strong> → <strong>Desviación
estándar de la rugosidad</strong>.</p></li>
<li><p><strong><span class="math inline">\(\rho = -0.6\)</span></strong>
→ <strong>Correlación de Pearson entre diámetro y
rugosidad</strong>.</p></li>
</ul>
<p>Esta matriz describe la <strong>dispersión conjunta de ambas
variables</strong>, donde la <strong>covarianza negativa indica que un
mayor diámetro tiende a estar asociado con una menor
rugosidad</strong>.</p>
<hr />
<p><strong>Función de densidad conjunta</strong>:</p>
<p>Dado que el <strong>diámetro del eje</strong> <span
class="math inline">\(X\)</span> y la <strong>rugosidad
superficial</strong> <span class="math inline">\(Y\)</span> siguen una
<strong>distribución normal bivariada</strong>, su <strong>función de
densidad conjunta</strong> está dada por:</p>
<p><span class="math display">\[
\scriptsize
f(x, y) = \frac{1}{2\pi \sigma_X \sigma_Y \sqrt{1 - \rho^2}}
\exp \left( -\frac{1}{2(1 - \rho^2)}
\left[ \frac{(x - \mu_X)^2}{\sigma_X^2} + \frac{(y -
\mu_Y)^2}{\sigma_Y^2} - 2\rho \frac{(x - \mu_X)(y - \mu_Y)}{\sigma_X
\sigma_Y} \right] \right)
\]</span></p>
<p>Sustituyendo los valores de los parámetros:</p>
<p><span class="math display">\[
\mu_X = 50.00, \quad \sigma_X = 0.015, \quad \mu_Y = 1.0, \quad \sigma_Y
= 0.2, \quad \rho = -0.6
\]</span></p>
<p><span class="math display">\[
\tiny
f(x, y) = \frac{1}{2\pi (0.015)(0.2) \sqrt{1 - (-0.6)^2}}
\exp \left( -\frac{1}{2(1 - (-0.6)^2)}
\left[ \frac{(x - 50.00)^2}{0.015^2} + \frac{(y - 1.0)^2}{0.2^2} -
2(-0.6) \frac{(x - 50.00)(y - 1.0)}{(0.015)(0.2)} \right] \right)
\]</span></p>
<p>Calculando los términos constantes:</p>
<p><span class="math display">\[
\scriptsize
f(x, y) = \frac{1}{2\pi (0.015)(0.2) \times 0.8}
\exp \left( -\frac{1}{1.6}
\left[ 4444(x - 50.00)^2 + 25(y - 1.0)^2 + 4.0(x - 50.00)(y - 1.0)
\right] \right)
\]</span></p>
<hr />
<p><strong>Representación gráfica de la función de densidad
conjunta</strong></p>
<p>Los códigos de <strong>R</strong> para dibujar la distribución normal
bivariada son los siguientes:</p>
<pre>
# Cargar librerías necesarias
library(mvtnorm)  # Para la función dmvnorm()
library(rgl)  # Para gráficos 3D interactivos

# Definir parámetros de la distribución normal bivariada
mu_X <- 50.00   # Media del diametro
sigma_X <- 0.015  # Desviación estándar del diametro (ajustada)
mu_Y <- 1.0     # Media de la rugosidad (ajustada)
sigma_Y <- 0.2   # Desviación estándar de la rugosidad (ajustada)
rho <- -0.6      # Correlación (ajustada)

# Crear la matriz de covarianza
Sigma <- matrix(c(sigma_X^2, rho * sigma_X * sigma_Y, 
                  rho * sigma_X * sigma_Y, sigma_Y^2), 
                ncol = 2)

# Definir el rango de valores para X y Y
x_vals <- seq(49.96, 50.04, length.out = 50)  # Ajustado a la nueva variabilidad
y_vals <- seq(0.5, 1.5, length.out = 50)  # Ajustado a la nueva rugosidad

# Crear una cuadrícula de puntos para evaluar la densidad
grid <- expand.grid(X = x_vals, Y = y_vals)

# Calcular la densidad conjunta usando dmvnorm() de mvtnorm
grid$Density <- dmvnorm(grid, mean = c(mu_X, mu_Y), sigma = Sigma)

# Convertir datos en matriz para gráfico 3D
z_matrix <- matrix(grid$Density, nrow = length(x_vals), ncol = length(y_vals))

# Abrir dispositivo de gráfico 3D en RGL
open3d()
par3d(windowRect = c(50, 50, 900, 900))  # Ajustar tamaño de la ventana

# Graficar la campana bivariada en 3D con ejes visibles
persp3d(x_vals, y_vals, z_matrix, col = "lightblue", alpha = 0.9,
        xlab = "", ylab = "", zlab = "", axes = TRUE,  # Mantener ejes sin etiquetas predeterminadas
        theta = 45, phi = 30, expand = 0.8, zoom = 0.9)

# Ajustar tamaño de etiquetas de los ejes para evitar superposición
par3d(cex = 1.0)

# Agregar nombres de los ejes manualmente sin acentos
text3d(x = 50.05, y = 1.0, z = 0, texts = "Diametro del eje (mm)", adj = c(1, 0))
text3d(x = 49.96, y = 1.5, z = 0, texts = "Rugosidad superficial (um)", adj = c(0, 1))

# Guardar el gráfico en un archivo PNG con buena resolución
rgl.snapshot("densidad_bivariada.png", fmt = "png")

# Cerrar el dispositivo gráfico correctamente
close3d()
</pre>
<pre class="r"><code># Cargar librerías necesarias
library(mvtnorm)  # Para la función dmvnorm()
library(rgl)  # Para gráficos 3D interactivos

# Definir parámetros de la distribución normal bivariada
mu_X &lt;- 50.00   # Media del diametro
sigma_X &lt;- 0.015  # Desviación estándar del diametro (ajustada)
mu_Y &lt;- 1.0     # Media de la rugosidad (ajustada)
sigma_Y &lt;- 0.2   # Desviación estándar de la rugosidad (ajustada)
rho &lt;- -0.6      # Correlación (ajustada)

# Crear la matriz de covarianza
Sigma &lt;- matrix(c(sigma_X^2, rho * sigma_X * sigma_Y, 
                  rho * sigma_X * sigma_Y, sigma_Y^2), 
                ncol = 2)

# Definir el rango de valores para X y Y
x_vals &lt;- seq(49.96, 50.04, length.out = 50)  # Ajustado a la nueva variabilidad
y_vals &lt;- seq(0.5, 1.5, length.out = 50)  # Ajustado a la nueva rugosidad

# Crear una cuadrícula de puntos para evaluar la densidad
grid &lt;- expand.grid(X = x_vals, Y = y_vals)

# Calcular la densidad conjunta usando dmvnorm() de mvtnorm
grid$Density &lt;- dmvnorm(grid, mean = c(mu_X, mu_Y), sigma = Sigma)

# Convertir datos en matriz para gráfico 3D
z_matrix &lt;- matrix(grid$Density, nrow = length(x_vals), ncol = length(y_vals))

# Abrir dispositivo de gráfico 3D en RGL
# open3d()
# par3d(windowRect = c(50, 50, 900, 900))  # Ajustar tamaño de la ventana

# Graficar la campana bivariada en 3D con ejes visibles
persp3d(x_vals, y_vals, z_matrix, col = &quot;lightblue&quot;, alpha = 0.9,
        xlab = &quot;&quot;, ylab = &quot;&quot;, zlab = &quot;&quot;, axes = TRUE,  # Mantener ejes sin etiquetas predeterminadas
        theta = 45, phi = 30, expand = 0.8, zoom = 0.9)

# Ajustar tamaño de etiquetas de los ejes para evitar superposición
par3d(cex = 1.0)

# Agregar nombres de los ejes manualmente sin acentos
text3d(x = 50.05, y = 1.0, z = 0, texts = &quot;Diametro del eje (mm)&quot;, adj = c(1, 0))
text3d(x = 49.96, y = 1.5, z = 0, texts = &quot;Rugosidad superficial (um)&quot;, adj = c(0, 1))

# Guardar el gráfico en un archivo PNG con buena resolución
rgl.snapshot(&quot;densidad_bivariada.png&quot;, fmt = &quot;png&quot;)

# Cerrar el dispositivo gráfico correctamente
close3d()</code></pre>
<br/><br/>
<center>
<img src="img/fig280.png" width="80%" style="display: block; margin: auto;" />
</center>
<p><strong>Figura 2.80</strong> Densidad conjunta de la normal
bivariada. Los ejes <span class="math inline">\(X\)</span> y <span
class="math inline">\(Y\)</span> corresponde a las variables del del
diámetro y rugosidad, mientras que la altura corresponde a la densidad
conjunta. <br/><br/></p>
<p>Los códigos de <strong>R</strong> para crear el mapa de calor y
curvas de nivel de la distribución normal bivariada son los
siguientes:</p>
<pre>
# Cargar librerías necesarias
library(ggplot2)
library(mvtnorm)  # Para usar dmvnorm()
library(reshape2)  # Para convertir la matriz en formato adecuado para ggplot

# Definir parámetros de la distribución normal bivariada
mu_X <- 50.00   # Media del diámetro
sigma_X <- 0.015  # Desviación estándar del diámetro (ajustada)
mu_Y <- 1.0     # Media de la rugosidad (ajustada)
sigma_Y <- 0.2   # Desviación estándar de la rugosidad (ajustada)
rho <- -0.6      # Correlación (ajustada)

# Crear la matriz de covarianza
Sigma <- matrix(c(sigma_X^2, rho * sigma_X * sigma_Y, 
                  rho * sigma_X * sigma_Y, sigma_Y^2), 
                ncol = 2)

# Definir el rango de valores para X y Y
x_vals <- seq(49.96, 50.04, length.out = 100)  # Ajustado a la nueva variabilidad
y_vals <- seq(0.5, 1.5, length.out = 100)  # Ajustado a la nueva rugosidad

# Crear una cuadrícula de puntos para evaluar la densidad
grid <- expand.grid(X = x_vals, Y = y_vals)

# Calcular la densidad conjunta usando dmvnorm() de mvtnorm
grid$Density <- dmvnorm(grid, mean = c(mu_X, mu_Y), sigma = Sigma)

# Graficar la densidad en 3D con ggplot (corregido)
plot_niv <- ggplot(grid, aes(x = X, y = Y)) +
  geom_raster(aes(fill = Density), interpolate = TRUE) +  # Mapa de calor de densidad
  stat_contour(aes(z = Density), bins = 10, color = "black") +  # Curvas de nivel sin leyenda
  scale_fill_gradient(low = "blue", high = "red") +
  guides(color = "none") +  # Elimina la leyenda de los niveles de densidad
  labs(title = "Densidad conjunta del diámetro y la rugosidad",
       x = "Diámetro del eje (mm)",
       y = "Rugosidad superficial (um)",
       fill = "Densidad") +
  theme_minimal()

print(plot_niv)
</pre>
<pre class="r"><code># Cargar librerías necesarias
library(ggplot2)
library(mvtnorm)  # Para usar dmvnorm()
library(reshape2)  # Para convertir la matriz en formato adecuado para ggplot

# Definir parámetros de la distribución normal bivariada
mu_X &lt;- 50.00   # Media del diámetro
sigma_X &lt;- 0.015  # Desviación estándar del diámetro (ajustada)
mu_Y &lt;- 1.0     # Media de la rugosidad (ajustada)
sigma_Y &lt;- 0.2   # Desviación estándar de la rugosidad (ajustada)
rho &lt;- -0.6      # Correlación (ajustada)

# Crear la matriz de covarianza
Sigma &lt;- matrix(c(sigma_X^2, rho * sigma_X * sigma_Y, 
                  rho * sigma_X * sigma_Y, sigma_Y^2), 
                ncol = 2)

# Definir el rango de valores para X y Y
x_vals &lt;- seq(49.96, 50.04, length.out = 100)  # Ajustado a la nueva variabilidad
y_vals &lt;- seq(0.5, 1.5, length.out = 100)  # Ajustado a la nueva rugosidad

# Crear una cuadrícula de puntos para evaluar la densidad
grid &lt;- expand.grid(X = x_vals, Y = y_vals)

# Calcular la densidad conjunta usando dmvnorm() de mvtnorm
grid$Density &lt;- dmvnorm(grid, mean = c(mu_X, mu_Y), sigma = Sigma)

# Graficar la densidad en 3D con ggplot (corregido)
plot_niv &lt;- ggplot(grid, aes(x = X, y = Y)) +
  geom_raster(aes(fill = Density), interpolate = TRUE) +  # Mapa de calor de densidad
  stat_contour(aes(z = Density), bins = 10, color = &quot;black&quot;) +  # Curvas de nivel sin leyenda
  scale_fill_gradient(low = &quot;blue&quot;, high = &quot;red&quot;) +
  guides(color = &quot;none&quot;) +  # Elimina la leyenda de los niveles de densidad
  labs(title = &quot;Densidad conjunta del diámetro y la rugosidad&quot;,
       x = &quot;Diámetro del eje (mm)&quot;,
       y = &quot;Rugosidad superficial (um)&quot;,
       fill = &quot;Densidad&quot;) +
  theme_minimal()

# print(plot_niv)</code></pre>
<p>La <strong>Figura 2.80</strong> muestra la densidad conjunta de la
normal bivariada del problema en estudio.</p>
<p>La <strong>Figura 2.81</strong> representa la <strong>distribución de
densidad conjunta del diámetro del eje <span
class="math inline">\(X\)</span> y la rugosidad superficial <span
class="math inline">\(Y\)</span></strong> mediante un <strong>mapa de
calor y curvas de nivel</strong>, donde se destacan los siguientes
aspectos:</p>
<ul>
<li><p><strong>Las zonas en rojo indican los valores más probables de
diámetro y rugosidad</strong>, es decir, las combinaciones de <span
class="math inline">\(X\)</span> y <span
class="math inline">\(Y\)</span> que ocurren con mayor frecuencia en el
proceso de mecanizado.</p></li>
<li><p><strong>Las zonas en azul representan valores menos
probables</strong>, indicando combinaciones de diámetro y rugosidad que
se presentan con menor frecuencia en la producción.</p></li>
<li><p><strong>El pico de densidad (zona roja central) se encuentra
cerca de (50.00, 1.0)</strong>, lo que coincide con el <strong>vector de
medias</strong> de la distribución, reflejando que estos valores son los
más comunes en el proceso de fabricación.</p></li>
<li><p><strong>La forma elíptica inclinada de las curvas de nivel
refleja la estructura de la covarianza</strong>. La inclinación negativa
de la elipse confirma que la <strong>correlación es <span
class="math inline">\(\rho = -0.6\)</span></strong>, lo que indica que
<strong>un mayor diámetro tiende a estar asociado con una menor
rugosidad superficial</strong>.</p></li>
</ul>
<br/><br/>
<center>
<img src="img/fig281.png" width="80%" style="display: block; margin: auto;" />
<strong>Figura 2.81</strong> Curvas de nivel de la densidad conjunta de
la normal bivariada.
</center>
<p><br/><br/></p>
<hr />
<p><strong>Cómputo de probabilidad conjunta:</strong></p>
<p>Un cliente requiere que los ejes fabricados cumplan con las
siguientes condiciones:</p>
<ul>
<li><p><strong>Diámetro del eje <span
class="math inline">\(X\)</span></strong>: Entre <strong>49.98 mm y
50.02 mm</strong>.</p></li>
<li><p><strong>Rugosidad superficial del eje <span
class="math inline">\(Y\)</span></strong>: Entre <strong>0.6 y 1.2
μm</strong>.</p></li>
</ul>
<p>Se busca calcular la probabilidad conjunta de que un eje seleccionado
al azar cumpla con ambas especificaciones. Como ambas variables son
continuas en la normal bivariada es necesario integrar la función de
densidad conjunta como se muestra a continuación:</p>
<p><span class="math display">\[
P(49.98 \leq X \leq 50.02, 0.6&lt; Y &lt; 1.2)=\int_{49.98}^{50.02}
\int_{0.6}^{1.2} f_{X,Y}(x, y) \, dy \, dx
\]</span></p>
<p>donde <span class="math inline">\(f_{X,Y}(x,y)\)</span> es la
<strong>función de densidad conjunta de la normal
bivariada</strong>.</p>
<p><br/> Los códigos de <strong>R</strong> para calcular la probabiidad
conjunta son los siguientes:</p>
<pre>
# Cargar librerías necesarias
library(mvtnorm)  # Para calcular probabilidades en la normal bivariada

# Definir los parámetros de la normal bivariada
mu_X <- 50.00   # Media del diámetro
sigma_X <- 0.015  # Desviación estándar del diámetro (ajustada)
mu_Y <- 1.0     # Media de la rugosidad (ajustada)
sigma_Y <- 0.2   # Desviación estándar de la rugosidad (ajustada)
rho <- -0.6      # Correlación (ajustada)

# Crear la matriz de covarianza
Sigma <- matrix(c(sigma_X^2, rho * sigma_X * sigma_Y, 
                  rho * sigma_X * sigma_Y, sigma_Y^2), 
                ncol = 2)

# Definir los límites del intervalo para X y Y
x_min <- 49.98
x_max <- 50.02
y_min <- 0.6
y_max <- 1.2

# Calcular la probabilidad P(49.98 ≤ X ≤ 50.02, 0.6 < Y < 1.2)
probabilidad <- pmvnorm(lower = c(x_min, y_min), upper = c(x_max, y_max),
                        mean = c(mu_X, mu_Y), sigma = Sigma)

# Mostrar el resultado
probabilidad
</pre>
<pre class="r"><code># Cargar librerías necesarias
library(mvtnorm)  # Para calcular probabilidades en la normal bivariada

# Definir los parámetros de la normal bivariada
mu_X &lt;- 50.00   # Media del diámetro
sigma_X &lt;- 0.015  # Desviación estándar del diámetro (ajustada)
mu_Y &lt;- 1.0     # Media de la rugosidad (ajustada)
sigma_Y &lt;- 0.2   # Desviación estándar de la rugosidad (ajustada)
rho &lt;- -0.6      # Correlación (ajustada)

# Crear la matriz de covarianza
Sigma &lt;- matrix(c(sigma_X^2, rho * sigma_X * sigma_Y, 
                  rho * sigma_X * sigma_Y, sigma_Y^2), 
                ncol = 2)

# Definir los límites del intervalo para X y Y
x_min &lt;- 49.98
x_max &lt;- 50.02
y_min &lt;- 0.6
y_max &lt;- 1.2

# Calcular la probabilidad P(49.98 ≤ X ≤ 50.02, 0.6 &lt; Y &lt; 1.2)
probabilidad &lt;- pmvnorm(lower = c(x_min, y_min), upper = c(x_max, y_max),
                        mean = c(mu_X, mu_Y), sigma = Sigma)

# Mostrar el resultado
probabilidad</code></pre>
<pre><code>## [1] 0.6979057
## attr(,&quot;error&quot;)
## [1] 1e-15
## attr(,&quot;msg&quot;)
## [1] &quot;Normal Completion&quot;</code></pre>
<p>El resultado de la probabilidad conjunta es <strong>0.6979</strong>,
lo que indica que, en una <strong>producción a gran escala</strong>,
aproximadamente <strong>el 69.8% de las piezas fabricadas cumplen con
los requisitos del cliente</strong>:</p>
<ul>
<li><p><strong>Diámetros entre 49.98 mm y 50.02 mm</strong>.</p></li>
<li><p><strong>Rugosidad superficial entre 0.6 y 1.2
μm</strong>.</p></li>
</ul>
<p>Existe un <strong>30.2% de piezas fuera de tolerancia</strong>, lo
que podría requerir ajustes en el proceso de fabricación.</p>
<hr />
<p><strong>Cómputo de probabilidad condicional:</strong></p>
<p>Se busca calcular la probabilidad condicional de <span
class="math inline">\(Y\)</span> condicionada a un rango de valores para
<span class="math inline">\(X\)</span>:</p>
<p><span class="math display">\[
P(Y &lt; 1.2 \mid 49.98 \leq X \leq 50.02)=\frac{P(49.98 \leq X \leq
50.02, Y &lt; 1.2)}{P(49.98 \leq X \leq 50.02)}
\]</span></p>
<p>Cada expresión se determina como:</p>
<ul>
<li>El numerador de la fracción:</li>
</ul>
<p><span class="math display">\[
P(49.98 \leq X \leq 50.02, Y &lt; 1.2) =
\int_{49.98}^{50.02} \int_{0}^{1.2} f_{X,Y}(x, y) \, dy \, dx
\]</span></p>
<ul>
<li>El denominador de la fracción:</li>
</ul>
<p><span class="math display">\[
P(49.98 \leq X \leq 50.02) =
\int_{49.98}^{50.02}\int_{0}^{\infty} f_{X,Y}(x, y) \, dy \, dx
\]</span></p>
<p><br/> Los códigos para determinar la probabilidad condicional con
<strong>R</strong> son:</p>
<pre>
# Cargar librerías necesarias
library(mvtnorm)  # Para calcular probabilidades en la normal bivariada

# Definir los parámetros de la normal bivariada
mu_X <- 50.00   # Media del diámetro
sigma_X <- 0.015  # Desviación estándar del diámetro (ajustada)
mu_Y <- 1.0     # Media de la rugosidad (ajustada)
sigma_Y <- 0.2   # Desviación estándar de la rugosidad (ajustada)
rho <- -0.6      # Correlación (ajustada)

# Crear la matriz de covarianza
Sigma <- matrix(c(sigma_X^2, rho * sigma_X * sigma_Y, 
                  rho * sigma_X * sigma_Y, sigma_Y^2), 
                ncol = 2)

# Definir los límites para el diámetro en especificación
x_min <- 49.98
x_max <- 50.02

# Definir el límite superior para la rugosidad
y_max <- 1.2

# Calcular la probabilidad conjunta P(49.98 ≤ X ≤ 50.02, Y < 1.2)
probabilidad_conjunta <- pmvnorm(lower = c(x_min, -Inf), upper = c(x_max, y_max),
                                 mean = c(mu_X, mu_Y), sigma = Sigma)

# Calcular la probabilidad marginal P(49.98 ≤ X ≤ 50.02)
probabilidad_x <- pmvnorm(lower = c(x_min, -Inf), upper = c(x_max, Inf),
                          mean = c(mu_X, mu_Y), sigma = Sigma)

# Calcular la probabilidad condicional
probabilidad_condicional <- probabilidad_conjunta / probabilidad_x

# Mostrar el resultado
probabilidad_condicional
</pre>
<pre class="r"><code># Cargar librerías necesarias
library(mvtnorm)  # Para calcular probabilidades en la normal bivariada

# Definir los parámetros de la normal bivariada
mu_X &lt;- 50.00   # Media del diámetro
sigma_X &lt;- 0.015  # Desviación estándar del diámetro (ajustada)
mu_Y &lt;- 1.0     # Media de la rugosidad (ajustada)
sigma_Y &lt;- 0.2   # Desviación estándar de la rugosidad (ajustada)
rho &lt;- -0.6      # Correlación (ajustada)

# Crear la matriz de covarianza
Sigma &lt;- matrix(c(sigma_X^2, rho * sigma_X * sigma_Y, 
                  rho * sigma_X * sigma_Y, sigma_Y^2), 
                ncol = 2)

# Definir los límites para el diámetro en especificación
x_min &lt;- 49.98
x_max &lt;- 50.02

# Definir el límite superior para la rugosidad
y_max &lt;- 1.2

# Calcular la probabilidad conjunta P(49.98 ≤ X ≤ 50.02, Y &lt; 1.2)
probabilidad_conjunta &lt;- pmvnorm(lower = c(x_min, -Inf), upper = c(x_max, y_max),
                                 mean = c(mu_X, mu_Y), sigma = Sigma)

# Calcular la probabilidad marginal P(49.98 ≤ X ≤ 50.02)
probabilidad_x &lt;- pmvnorm(lower = c(x_min, -Inf), upper = c(x_max, Inf),
                          mean = c(mu_X, mu_Y), sigma = Sigma)

# Calcular la probabilidad condicional
probabilidad_condicional &lt;- probabilidad_conjunta / probabilidad_x

# Mostrar el resultado
probabilidad_condicional</code></pre>
<pre><code>## [1] 0.8663515
## attr(,&quot;error&quot;)
## [1] 1e-15
## attr(,&quot;msg&quot;)
## [1] &quot;Normal Completion&quot;</code></pre>
<p>El resultado de la probabilidad condicional es
<strong>0.8664</strong>, lo que indica que <strong>si un eje fabricado
tiene su diámetro dentro del rango especificado de <span
class="math inline">\(49.98 \leq X \leq 50.02\)</span>, hay un 0.8664 de
probabilidad de que su rugosidad sea menor a 1.2 μm</strong>. Por tanto,
en una <strong>producción a gran escala</strong>, esto significa que
aproximadamente <strong>el 86.64% de los ejes con un diámetro entre
49.98 mm y 50.02 mm cumplirán con el requisito de rugosidad menor a 1.2
μm</strong>.</p>
<hr />
<p><strong>Cómputo de esperanza condicional:</strong></p>
<p>Se busca calcular la esperanza condicional de <span
class="math inline">\(Y\)</span> dado un valor específico de <span
class="math inline">\(X =  50.01\)</span>:</p>
<p><span class="math display">\[
E[Y \mid X = 50.01]
\]</span></p>
<p>La esperanza condicional de <span class="math inline">\(Y\)</span>
dado un valor específico de <span class="math inline">\(X = x\)</span>
se define como:</p>
<p><span class="math display">\[
E[Y \mid X = x] = \int_{-\infty}^{\infty} y f_{Y|X}(y|x) \, dy
\]</span></p>
<p>donde <span class="math inline">\(f_{Y|X}(y|x)\)</span> es la
<strong>función de densidad condicional de <span
class="math inline">\(Y\)</span> dado <span class="math inline">\(X =
x\)</span></strong>.</p>
<p>La <strong>densidad condicional</strong> de <span
class="math inline">\(Y\)</span> dado un valor específico de <span
class="math inline">\(X = x\)</span> se define como:</p>
<p><span class="math display">\[
f_{Y|X}(y|x) = \frac{f_{X,Y}(x,y)}{f_X(x)}
\]</span></p>
<p>donde:</p>
<ul>
<li><p><span class="math inline">\(f_{X,Y}(x,y)\)</span> es la
<strong>densidad conjunta</strong> de <span class="math inline">\((X,
Y)\)</span>.</p></li>
<li><p><span class="math inline">\(f_X(x)\)</span> es la
<strong>densidad marginal</strong> de <span
class="math inline">\(X\)</span>, obtenida integrando la función de
densidad conjunta sobre <span class="math inline">\(Y\)</span>.</p></li>
</ul>
<p><span class="math display">\[
f_{Y|X}(y|x) = \frac{1}{\sqrt{2\pi \sigma_{Y|X}^2}} \exp\left(-\frac{(y
- \mu_{Y|X})^2}{2\sigma_{Y|X}^2} \right)
\]</span></p>
<p>donde:</p>
<ul>
<li><p><span class="math inline">\(\mu_{Y|X} = \mu_Y + \rho
\frac{\sigma_Y}{\sigma_X} (x - \mu_X)\)</span> es la <strong>media
condicional</strong>.</p></li>
<li><p><span class="math inline">\(\sigma_{Y|X}^2 = \sigma_Y^2 (1 -
\rho^2)\)</span> es la <strong>varianza condicional</strong>.</p></li>
</ul>
<p>La <strong>esperanza condicional de <span
class="math inline">\(Y\)</span> dado <span class="math inline">\(X =
x\)</span></strong> se define como:</p>
<p><span class="math display">\[
E[Y \mid X = x] = \int_{-\infty}^{\infty} y f_{Y|X}(y|x) \, dy
\]</span></p>
<p>Sustituyendo la densidad condicional:</p>
<p><span class="math display">\[
E[Y \mid X = x] = \int_{-\infty}^{\infty} y \cdot \frac{1}{\sqrt{2\pi
\sigma_{Y|X}^2}} \exp\left(-\frac{(y - \mu_{Y|X})^2}{2\sigma_{Y|X}^2}
\right) dy
\]</span></p>
<p>Entonces,</p>
<p><span class="math display">\[
E[Y \mid X = x] = \mu_{Y|X} = \mu_Y + \rho \frac{\sigma_Y}{\sigma_X} (x
- \mu_X)
\]</span></p>
<p>La esperanza condicional se determina en <strong>R</strong> con los
códigos:</p>
<pre>
# Definir los parámetros de la normal bivariada
mu_X <- 50.00   # Media del diámetro
sigma_X <- 0.015  # Desviación estándar del diámetro (ajustada)
mu_Y <- 1.0     # Media de la rugosidad (ajustada)
sigma_Y <- 0.2   # Desviación estándar de la rugosidad (ajustada)
rho <- -0.6      # Correlación (ajustada)

# Valor de X para calcular la esperanza condicional
x_given <- 50.01

# Calcular la esperanza condicional E[Y | X = x_given]
esperanza_condicional <- mu_Y + rho * (sigma_Y / sigma_X) * (x_given - mu_X)

# Mostrar el resultado
esperanza_condicional
</pre>
<pre class="r"><code># Definir los parámetros de la normal bivariada
mu_X &lt;- 50.00   # Media del diámetro
sigma_X &lt;- 0.015  # Desviación estándar del diámetro (ajustada)
mu_Y &lt;- 1.0     # Media de la rugosidad (ajustada)
sigma_Y &lt;- 0.2   # Desviación estándar de la rugosidad (ajustada)
rho &lt;- -0.6      # Correlación (ajustada)

# Valor de X para calcular la esperanza condicional
x_given &lt;- 50.01

# Calcular la esperanza condicional E[Y | X = x_given]
esperanza_condicional &lt;- mu_Y + rho * (sigma_Y / sigma_X) * (x_given - mu_X)

# Mostrar el resultado
esperanza_condicional</code></pre>
<pre><code>## [1] 0.92</code></pre>
<p>La <strong>esperanza condicional de la rugosidad</strong> dado un
diámetro fijo de <strong>50.01 mm</strong> es <strong>0.92 μm</strong>.
Esto significa que, en una <strong>producción a gran escala</strong>, el
<strong>promedio esperado de la rugosidad</strong> para los ejes que
tienen un diámetro de <strong>50.01 mm</strong> será de aproximadamente
<strong>0.92 μm</strong>.</p>
<p>Este resultado sugiere que <strong>si el diámetro de los ejes se
mantiene muy cerca de 50.01 mm</strong>, la rugosidad tenderá a estar
alrededor de <strong>0.92 μm</strong>, lo que puede ayudar a prever la
calidad superficial de los ejes fabricados.</p>
<hr />
<p><br/><br/> <strong>Relación con la regresión lineal</strong></p>
<p>Hasta este punto, se ha analizado la relación entre <strong>el
diámetro del eje <span class="math inline">\(X\)</span> y la rugosidad
superficial <span class="math inline">\(Y\)</span></strong>, evaluando
probabilidades conjuntas, condicionales y valores esperados en el
contexto del <strong>control de calidad en la fabricación de ejes
metálicos</strong>.</p>
<p>Sin embargo, el análisis realizado tiene una conexión importante con
la <strong>regresión lineal</strong>, una técnica ampliamente utilizada
en estadística para modelar relaciones entre variables.</p>
<ul>
<li><p><strong>Relación entre la esperanza condicional y la regresión
lineal</strong></p>
<p>En los cálculos anteriores, se determino que la <strong>esperanza
condicional de la rugosidad <span class="math inline">\(Y\)</span> dado
un diámetro específico <span class="math inline">\(X =
x\)</span></strong> está dada por la ecuación:</p>
<p><span class="math display">\[
E[Y \mid X = x] = \mu_Y + \rho \frac{\sigma_Y}{\sigma_X} (x - \mu_X)
\]</span></p>
<p>Esta ecuación es equivalente a la <strong>ecuación de una regresión
lineal simple</strong>:</p>
<p><span class="math display">\[
E[Y \mid X = x] = \beta_0 + \beta_1 x
\]</span></p>
<p>donde los coeficientes de regresión son:</p>
<ul>
<li><p><strong>Intercepto:</strong> <span class="math inline">\(\beta_0
= \mu_Y - \rho \frac{\sigma_Y}{\sigma_X} \mu_X\)</span></p></li>
<li><p><strong>Pendiente:</strong> <span class="math inline">\(\beta_1 =
\rho \frac{\sigma_Y}{\sigma_X}\)</span></p></li>
</ul>
<p><strong>¿Qué significa esto en el contexto del problema?</strong></p>
<ul>
<li><p>La ecuación muestra que se <strong>puede predecir la rugosidad
esperada en función del diámetro</strong>, lo que es clave para el
<strong>control de calidad</strong>.</p></li>
<li><p>La pendiente <strong><span
class="math inline">\(\beta_1\)</span></strong> nos indica la dirección
y magnitud del efecto del diámetro sobre la rugosidad.</p></li>
<li><p>Como <strong><span class="math inline">\(\rho &lt;
0\)</span></strong> en este problema, esto significa que <strong>un
mayor diámetro tiende a estar asociado con una menor
rugosidad</strong>.</p></li>
</ul></li>
<li><p><strong>Varianza condicional y dispersión en la
regresión</strong></p>
<p>La <strong>varianza condicional</strong> está dada por:</p>
<p><span class="math display">\[
Var(Y \mid X = x) = \sigma_Y^2 (1 - \rho^2)
\]</span></p>
<p>donde:</p>
<ul>
<li><p><span class="math inline">\(\sigma_Y^2\)</span> es la varianza
total de la rugosidad.</p></li>
<li><p><span class="math inline">\(\rho\)</span> es el
<strong>coeficiente de correlación</strong> entre <span
class="math inline">\(X\)</span> y <span
class="math inline">\(Y\)</span>.</p></li>
</ul>
<p>De esta expresión se puede decir en términos de control de calidad
que aunque <strong>se puede predecir un valor esperado de rugosidad para
un diámetro dado</strong>, siempre habrá <strong>cierta variabilidad
residual</strong> debida a otros factores en el proceso de fabricación
(herramientas, vibraciones, desgaste, etc.).</p>
<ul>
<li><p><strong>¿Cómo afecta el valor de <span
class="math inline">\(\rho\)</span>?</strong></p>
<ul>
<li><p>Si <span class="math inline">\(\rho = 0\)</span> <strong>(no hay
correlación entre diámetro y rugosidad)</strong>: <span
class="math inline">\(Var(Y \mid X = x) = \sigma_Y^2\)</span>. En
consecuencia, la varianza condicional <strong>no cambia</strong>, es
decir, la dispersión de la rugosidad es la misma independientemente del
valor de <span class="math inline">\(X\)</span>. En términos prácticos,
esto significa que <strong>el diámetro no aporta información útil para
predecir la rugosidad</strong>, por lo que controlar <span
class="math inline">\(X\)</span> no ayuda a mejorar la calidad del
acabado superficial.</p></li>
<li><p>Si <span class="math inline">\(\rho\)</span> está cerca de <span
class="math inline">\(\pm 1\)</span> <strong>(correlación fuerte entre
diámetro y rugosidad)</strong>: <span class="math inline">\(Var(Y \mid X
= x)\approx 0\)</span>. La varianza condicional se reduce
significativamente. <strong>Cuando <span class="math inline">\(\rho \to
\pm1\)</span>, la varianza condicional tiende a 0, lo que significa que
la rugosidad es totalmente predecible a partir del diámetro</strong>. En
términos industriales, esto implica que <strong>controlar <span
class="math inline">\(X\)</span> con precisión garantizaría la rugosidad
deseada, eliminando prácticamente la variabilidad en <span
class="math inline">\(Y\)</span></strong>.</p></li>
<li><p>Si <span class="math inline">\(\rho\)</span> es moderado (<span
class="math inline">\(-1 &lt; \rho &lt; 1\)</span>): La varianza
condicional es <strong>menor que la varianza total</strong> de <span
class="math inline">\(Y\)</span>, pero sigue habiendo cierta
variabilidad. <strong>A mayor <span
class="math inline">\(|\rho|\)</span>, menor será la varianza
condicional</strong>, lo que significa que <strong>la predicción de
rugosidad basada en el diámetro es más confiable</strong>. <strong>A
menor <span class="math inline">\(|\rho|\)</span>, mayor será la
variabilidad en la rugosidad, lo que indica que hay otros factores en el
proceso de mecanizado que influyen en <span
class="math inline">\(Y\)</span></strong>.</p></li>
</ul>
<p>En este problema, el coeficiente de correlación entre el
<strong>diámetro del eje <span class="math inline">\(X\)</span></strong>
y la <strong>rugosidad superficial <span
class="math inline">\(Y\)</span></strong> es <strong><span
class="math inline">\(\rho = -0.6\)</span></strong>.</p>
<p>La <strong>varianza condicional de <span
class="math inline">\(Y\)</span> dado <span
class="math inline">\(X\)</span></strong> está dada por:</p>
<p><span class="math display">\[
Var(Y \mid X = x) = \sigma_Y^2 (1 - \rho^2)
\]</span></p>
<p>Sustituyendo los valores del problema:</p>
<p><span class="math display">\[
Var(Y \mid X = x) = (0.2)^2 (1 - (-0.6)^2)
\]</span></p>
<p><span class="math display">\[
= 0.04 \times (1 - 0.36) = 0.04 \times 0.64 = 0.0256
\]</span></p>
<p>Tomando la raíz cuadrada para obtener la <strong>desviación estándar
condicional</strong>:</p>
<p><span class="math display">\[
\sigma_{Y \mid X} = \sqrt{0.0256} = 0.16
\]</span></p>
<p>Antes de considerar el diámetro <span
class="math inline">\(X\)</span>, la rugosidad tenía una desviación
estándar de <strong><span class="math inline">\(\sigma_Y = 0.2\)</span>
μm</strong>. Después de condicionar en <span
class="math inline">\(X\)</span>, la desviación estándar se reduce a
<strong><span class="math inline">\(\sigma_{Y|X} = 0.16\)</span>
μm</strong>, lo que significa que <strong>la dispersión en la rugosidad
disminuye un 20%</strong> cuando se conoce el diámetro. Por tanto, el
control del diámetro ayuda a reducir la incertidumbre en la
rugosidad.</p>
<p>Dado que <span class="math inline">\(|\rho|\)</span> no es cercano a
1, la reducción de la variabilidad en <span
class="math inline">\(Y\)</span> es moderada<strong>, lo que sugiere que
</strong>el control del diámetro es útil, pero no suficiente por sí solo
para garantizar una rugosidad óptima.</p></li>
</ul></li>
<li><p><strong>Relación entre la probabilidad condicional y la
regresión</strong>:</p>
<ul>
<li><p>Se ha calculado la <strong>probabilidad condicional</strong>:
<span class="math inline">\(P(Y &lt; 1.2 \mid 49.98 \leq X \leq
50.02)\)</span>, que mide <strong>qué tan probable es que la rugosidad
esté dentro del rango deseado cuando el diámetro está dentro de las
especificaciones</strong>.</p></li>
<li><p>En <strong>regresión lineal</strong>, se usa la ecuación de la
recta de regresión para hacer predicciones de <span
class="math inline">\(Y\)</span>, pero también se tiene en cuenta la
dispersión de los datos alrededor de la recta.</p></li>
<li><p>La probabilidad condicional intuitivamente se puede comparar
<strong>con el cálculo de la probabilidad de que los valores predichos
de <span class="math inline">\(Y\)</span>, más su variabilidad residual,
estén dentro de un intervalo de aceptación</strong>.</p></li>
</ul></li>
</ul>
</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
