<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Métodos y Simulación Estadística" />


<title> Simulación</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"> </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Inicio
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Probabilidad
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso101.html">Introducción</a>
    </li>
    <li>
      <a href="recurso102.html">Conceptos Básicos</a>
    </li>
    <li>
      <a href="recurso103.html">Enfoques y Postulados</a>
    </li>
    <li>
      <a href="recurso104.html">Tipos de Probabilidad</a>
    </li>
    <li>
      <a href="recurso104b.html">Independencia</a>
    </li>
    <li>
      <a href="recurso104c.html">Teorema de Bayes</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Variable Aleatoria
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso201.html">Variable Aleatoria: Univariado</a>
    </li>
    <li>
      <a href="recurso202.html">Valor Esperado</a>
    </li>
    <li>
      <a href="recurso203.html">Variables Conjuntas</a>
    </li>
    <li>
      <a href="recurso204.html">Modelos Discretos: Univariado</a>
    </li>
    <li>
      <a href="recurso205.html">Modelos Continuos: Univariado</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Inferencia Estadística
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso301.html">Conceptos Básicos</a>
    </li>
    <li>
      <a href="recurso302.html">Estimación Puntual</a>
    </li>
    <li>
      <a href="recurso305.html">Teorema del Límite Central</a>
    </li>
    <li>
      <a href="recurso303.html">Propiedades de los Estimadores</a>
    </li>
    <li>
      <a href="recurso304.html">Métodos de Estimación</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Intervalos de Confianza
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso401.html">Paramétrico: Una Población</a>
    </li>
    <li>
      <a href="recurso402.html">Paramétrico: Dos Poblaciones</a>
    </li>
    <li>
      <a href="recurso403.html">Estimación no Paramétrica</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Pruebas de Hipótesis
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso501.html">Introducción</a>
    </li>
    <li>
      <a href="recurso502.html">Paramétrico: Una Población</a>
    </li>
    <li>
      <a href="recurso503.html">Paramétrico: Dos Poblaciones</a>
    </li>
    <li>
      <a href="recurso504.html">Pruebas no Paramétricas</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Casos y Simulaciones
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso404.html">Caso 1</a>
    </li>
    <li>
      <a href="recurso405.html">Caso 2</a>
    </li>
    <li>
      <a href="recurso406.html">Simulación 1</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Referencias
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso1000.html">Referencias</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore"><span style="color:#686868">
<strong>Simulación</strong></span></h1>
<h4 class="author">Métodos y Simulación Estadística</h4>

</div>


</br></br>
<div class="caja-ejemplo">
<h3>
Ejemplo (simulación estadística):
</h3>
<p>
<p>Una fábrica de dispositivos electrónicos realiza <strong>pruebas de
calidad</strong> a cada lote de producción. Se sabe que, en promedio, el
<strong>10% de los productos presentan defectos</strong>. Suponiendo que
la cantidad de productos defectuosos en un lote sigue una
<strong>distribución Binomial</strong>, se realizarán varios análisis de
simulación.</p>
<ul>
<li><p>Cada lote contiene <strong>50 productos</strong>.</p></li>
<li><p>Cada producto puede estar <strong>defectuoso</strong> (<span
class="math inline">\(X=1\)</span>) o <strong>no defectuoso</strong>
(<span class="math inline">\(X=0\)</span>).</p></li>
<li><p>La probabilidad de que un producto sea defectuoso es
<strong><span class="math inline">\(p = 0.10\)</span></strong>.</p></li>
<li><p>Si se selecciona un lote de <strong>50 productos</strong>, el
número de productos defectuosos sigue una distribución binomial: <span
class="math display">\[ X \sim Bin(50, 0.10) \]</span></p></li>
</ul>
<p>donde <span class="math inline">\(X\)</span> representa la cantidad
de productos defectuosos en un lote de 50 productos.</p>
<p>Realiza el siguiente experimento computacional:</p>
<hr />
<ol style="list-style-type: lower-alpha">
<li><strong>Cálculo de probabilidad teórica</strong>: Calcula la
probabilidad de que en un lote de <strong>50 productos</strong> haya
exactamente <strong>5 defectuosos</strong> usando la distribución
binomial.</li>
</ol>
<p>La función de probabilidad de la distribución
<strong>Binomial</strong> se define como:</p>
<p><span class="math display">\[ P(X = k) = \binom{n}{k} p^k (1 - p)^{n
- k} \]</span></p>
<p>donde:</p>
<ul>
<li><p><span class="math inline">\(n = 50\)</span> es el número total de
ensayos (productos en un lote).</p></li>
<li><p><span class="math inline">\(k = 5\)</span> es el número de éxitos
(productos defectuosos).</p></li>
<li><p><span class="math inline">\(p = 0.10\)</span> es la probabilidad
de éxito (que un producto sea defectuoso).</p></li>
<li><p><span class="math inline">\(\binom{n}{k}\)</span> es el
coeficiente binomial, que se calcula como:</p></li>
</ul>
<p><span class="math display">\[ \binom{n}{k} = \frac{n!}{k!(n-k)!}
\]</span></p>
<p>Ahora, reemplazamos los valores en la fórmula. Primero se calcula el
coeficiente binomial:</p>
<pre>
bin_coeff <- choose(50, 5)
bin_coeff
</pre>
<pre class="r"><code>bin_coeff &lt;- choose(50, 5)
bin_coeff</code></pre>
Posteriormente se calcula la probabilidad
<pre>
prob_x_5 <- bin_coeff * (0.10^5) * (0.90^(50 - 5))
prob_x_5
</pre>
<pre class="r"><code>prob_x_5 &lt;- bin_coeff * (0.10^5) * (0.90^(50 - 5))
prob_x_5</code></pre>
La solución en <strong>R</strong> se puede calcular directamente con la
función de la distribución binomial, como se muestra acontinuación
<pre>
size <- 50  # Tamaño del lote
prob <- 0.10  # Probabilidad de defecto
x <- 5  # Número de defectuosos

p_x5 <- dbinom(x, size, prob)
p_x5
</pre>
<pre class="r"><code>size &lt;- 50  # Tamaño del lote
prob &lt;- 0.10  # Probabilidad de defecto
x &lt;- 5  # Número de defectuosos

p_x5 &lt;- dbinom(x, size, prob)
p_x5</code></pre>
<pre><code>## [1] 0.1849246</code></pre>
<p>La probabilidad de que 5 dispositivos sean defectuosos en un lote de
50 dispositivos es 0.1849. En términos prácticos, esto significa que, si
se selecciona un gran número de lotes de 50 dispositivos (por ejemplo
1000 lotes), aproximadamente el 18.5% de esos lotes contendrán
exactamente 5 dispositivos defectuosos.</p>
<hr />
<ol start="2" style="list-style-type: lower-alpha">
<li><strong>Simulación con una muestra grande</strong>: Genera
<strong>una muestra aleatoria</strong> de <strong>1000 lotes</strong>,
cada uno con <strong>50 productos</strong>. Calcula la frecuencia
relativa para <span class="math inline">\(X=5\)</span>, esto es <span
class="math inline">\(f_n(X=5)\)</span>. Compara e interpreta el
resultado frente a la probabilidad teórica.</li>
</ol>
<p>Usando los códigos siguientes se obtiene la frecuencia relativa:</p>
<pre>
set.seed(123)
n <- 1000  # Número de lotes
sim_data <- rbinom(n, size, prob)

# Frecuencia relativa de X = 5
f_x5 <- sum(sim_data == x) / n
f_x5
</pre>
<pre class="r"><code>set.seed(123)
n &lt;- 1000  # Número de lotes
sim_data &lt;- rbinom(n, size, prob)

# Frecuencia relativa de X = 5
f_x5 &lt;- sum(sim_data == x) / n
f_x5</code></pre>
<pre><code>## [1] 0.173</code></pre>
<p>La frecuencia relativa obtenida es 0.173, asegurando reproducibilidad
al fijar la semilla con <code>set.seed(123)</code>, lo que permite
generar la misma muestra cada vez que se ejecuta el código. Se observa
que este valor se aproxima a la probabilidad teórica de 0.1849, lo cual
es esperable dado que se seleccionó un gran número de lotes (en este
caso, 1000 lotes). A medida que el número de lotes aumenta, la
frecuencia relativa tiende a converger hacia la probabilidad teórica, en
concordancia con la Ley de los Grandes Números.</p>
<hr />
<ol start="3" style="list-style-type: lower-alpha">
<li><strong>Análisis de la variabilidad entre múltiples
muestras</strong>: Genera <strong>100 muestras independientes</strong>,
cada una con <strong>1000 lotes</strong>, y analiza la variabilidad de
la estimación de la probabilidad. Construye un gráfico de dispersión que
relacione la muestra y su frecuencia relativa, como también el valor de
la probabilidad teórica.</li>
</ol>
<p>Con los códigos siguientes se obtienen los resultados:</p>
<pre>
muestras <- 100
freq_rel_x5 <- numeric(muestras)

for (i in 1:muestras) {
  sim_data <- rbinom(n, size, prob)
  freq_rel_x5[i] <- sum(sim_data == x) / n
}

plot(1:muestras, freq_rel_x5, xlab = "Número de muestra", ylab = "Frecuencia relativa de X=5", main = "Variabilidad de la frecuencia relativa", pch = 19)
abline(h = p_x5, col = "red", lwd = 2)
</pre>
<pre class="r"><code>muestras &lt;- 100
freq_rel_x5 &lt;- numeric(muestras)

for (i in 1:muestras) {
  sim_data &lt;- rbinom(n, size, prob)
  freq_rel_x5[i] &lt;- sum(sim_data == x) / n
}

plot(1:muestras, freq_rel_x5, xlab = &quot;Número de muestra&quot;, ylab = &quot;Frecuencia relativa de X=5&quot;, main = &quot;Variabilidad de la frecuencia relativa&quot;, pch = 19)
abline(h = p_x5, col = &quot;red&quot;, lwd = 2)</code></pre>
<p><img src="recurso406_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>La gráfica muestra la variabilidad de la frecuencia relativa de <span
class="math inline">\(X=5\)</span> a lo largo de 100 repeticiones del
experimento, donde en cada repetición se extrajeron 1000 lotes de tamaño
50. Los puntos representan la frecuencia relativa obtenida en cada
repetición del experimento, mientras que la línea roja indica el valor
de la probabilidad teórica de 0.1849.</p>
<p>Se observa que las frecuencias relativas fluctúan en torno al valor
teórico de 0.1849, lo que refleja la variabilidad del muestreo. Aunque
hay dispersión en las observaciones, la mayoría de los valores se
concentran en un rango cercano a la probabilidad teórica. Este
comportamiento es consistente con la Ley de los Grandes Números, que
establece que conforme aumenta el número de repeticiones (mayor cantidad
de lotes), la frecuencia relativa tiende a acercarse a la probabilidad
teórica.</p>
<p>En conclusión, esta simulación ilustra cómo la frecuencia relativa se
estabiliza cerca del valor esperado teórico, pero puede presentar
fluctuaciones debido al muestreo aleatorio en cada repetición del
experimento.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li><strong>Impacto del tamaño muestral en la estimación de la
probabilidad</strong>: Analiza cómo cambia la frecuencia relativa de
<span class="math inline">\(X=5\)</span> al aumentar el tamaño de la
muestra.</li>
</ol>
<pre>
tamanos_muestra <- c(5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000)
freq_tamanos <- numeric(length(tamanos_muestra))

for (i in seq_along(tamanos_muestra)) {
  sim_data <- rbinom(tamanos_muestra[i], size, prob)
  freq_tamanos[i] <- sum(sim_data == x) / tamanos_muestra[i]
}

plot(tamanos_muestra, freq_tamanos, type = "b", xlab = "Tamaño de muestra (número de lotes)", ylab = "Frecuencia relativa de X=5", main = "Impacto del tamaño muestral")
abline(h = p_x5, col = "red", lwd = 2)
</pre>
<pre class="r"><code>tamanos_muestra &lt;- c(5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000)
freq_tamanos &lt;- numeric(length(tamanos_muestra))

for (i in seq_along(tamanos_muestra)) {
  sim_data &lt;- rbinom(tamanos_muestra[i], size, prob)
  freq_tamanos[i] &lt;- sum(sim_data == x) / tamanos_muestra[i]
}

plot(tamanos_muestra, freq_tamanos, type = &quot;b&quot;, xlab = &quot;Tamaño de muestra (número de lotes)&quot;, ylab = &quot;Frecuencia relativa de X=5&quot;, main = &quot;Impacto del tamaño muestral&quot;)
abline(h = p_x5, col = &quot;red&quot;, lwd = 2)</code></pre>
<p><img src="recurso406_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>El gráfico muestra el impacto del tamaño muestral en la frecuencia
relativa de <span class="math inline">\(X=5\)</span> a medida que
aumenta el número de lotes (cada uno con tamaño 50). La línea roja
representa la probabilidad teórica de 0.1849, mientras que los puntos y
la línea negra conectada indican la frecuencia relativa obtenida en cada
tamaño muestral.</p>
<p>Para tamaños de muestra pequeños (pocos lotes), la frecuencia
relativa presenta una alta variabilidad, con valores que oscilan
ampliamente por encima y por debajo de la probabilidad teórica. A medida
que el número de lotes aumenta, la frecuencia relativa tiende a
estabilizarse alrededor de la probabilidad teórica. Se observa una menor
dispersión en las estimaciones conforme aumenta el tamaño muestral.</p>
<p>Este comportamiento es consistente con la Ley de los Grandes Números,
que establece que, a medida que se toman más muestras, la frecuencia
relativa de un evento tiende a aproximarse a su probabilidad
teórica.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li><strong>Convergencia de la media muestral</strong>: Genera
<strong>100 muestras independientes</strong>, cada una con <strong>1000
lotes</strong>, y analiza la convergencia de la media muestral.</li>
</ol>
<pre>
media_muestras <- numeric(muestras)

for (i in 1:muestras) {
  sim_data <- rbinom(n, size, prob)
  media_muestras[i] <- mean(sim_data)
}

plot(1:muestras, media_muestras, xlab = "Número de muestra", ylab = "Media muestral de defectuosos", main = "Convergencia de la media muestral", pch = 19)
abline(h = size * prob, col = "red", lwd = 2)
</pre>
<pre class="r"><code>media_muestras &lt;- numeric(muestras)

for (i in 1:muestras) {
  sim_data &lt;- rbinom(n, size, prob)
  media_muestras[i] &lt;- mean(sim_data)
}

plot(1:muestras, media_muestras, xlab = &quot;Número de muestra&quot;, ylab = &quot;Media muestral de defectuosos&quot;, main = &quot;Convergencia de la media muestral&quot;, pch = 19)
abline(h = size * prob, col = &quot;red&quot;, lwd = 2)</code></pre>
<p><img src="recurso406_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>El gráfico representa la media muestral del número de dispositivos
defectuosos en 100 muestras, donde cada muestra está compuesta por 1000
lotes de tamaño 50. La línea roja indica la media teórica esperada de
5.</p>
<p>Cada punto en el gráfico representa la media de defectuosos en una de
las 100 muestras de 1000 lotes. Se observa que las medias muestrales
fluctúan en torno a 5, pero con variaciones ligeras entre muestras. La
dispersión de los puntos es reducida y las medias tienden a agruparse
muy cerca del valor teórico de 5. Este comportamiento es esperado, dado
que la Ley de los Grandes Números garantiza que la media muestral
converge a la media teórica conforme aumenta el tamaño de cada
muestra.</p>
<ol start="6" style="list-style-type: lower-alpha">
<li><strong>Impacto del tamaño muestral en la media estimada</strong>:
Analiza cómo la media muestral se estabiliza al aumentar el tamaño de la
muestra.</li>
</ol>
<pre>
media_tamanos <- numeric(length(tamanos_muestra))

for (i in seq_along(tamanos_muestra)) {
  sim_data <- rbinom(tamanos_muestra[i], size, prob)
  media_tamanos[i] <- mean(sim_data)
}

plot(tamanos_muestra, media_tamanos, type = "b", xlab = "Tamaño de muestra (número de lotes)", ylab = "Media de defectuosos", main = "Impacto del tamaño muestral en la media")
abline(h = size * prob, col = "red", lwd = 2)
</pre>
<pre class="r"><code>media_tamanos &lt;- numeric(length(tamanos_muestra))

for (i in seq_along(tamanos_muestra)) {
  sim_data &lt;- rbinom(tamanos_muestra[i], size, prob)
  media_tamanos[i] &lt;- mean(sim_data)
}

plot(tamanos_muestra, media_tamanos, type = &quot;b&quot;, xlab = &quot;Tamaño de muestra (número de lotes)&quot;, ylab = &quot;Media de defectuosos&quot;, main = &quot;Impacto del tamaño muestral en la media&quot;)
abline(h = size * prob, col = &quot;red&quot;, lwd = 2)</code></pre>
<p><img src="recurso406_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>El gráfico muestra el impacto del tamaño muestral en la media, donde
el eje X representa el número de lotes considerados y el eje Y la media
de defectuosos observada en cada tamaño muestral. La línea roja indica
la media teórica esperada de 5.</p>
<p>Para tamaños de muestra pequeños (pocos lotes), la media muestral
fluctúa significativamente alrededor del valor teórico. Se observan
desviaciones grandes, con valores que pueden estar muy por debajo o por
encima de la media esperada. A medida que el número de lotes
considerados aumenta, la media muestral se acerca progresivamente al
valor esperado de 5 defectuosos por lote. La variabilidad disminuye y
las oscilaciones se reducen, indicando una mayor estabilidad en la
estimación de la media. Esto confirma el efecto de la Ley de los Grandes
Números, que establece que la media muestral converge a la media teórica
cuando el tamaño muestral aumenta.</p>
</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
